package com.juliar.nodes;

/**
 * Created by don on 3/25/17.
 */
public enum NodeType {
    AddType,
    AggregateType,
    AssignmentType,
    BinaryType,
    BooleanType,
    BooleanOperatorType,
    BreakType,
    CompliationUnitType,
    CommandType,
    EqualEqualType,
    EqualSignType,
    ExpressionType,
    FinalType,
    FunctionaCallType,
    FunctionDeclType,
    IfExprType,
    IntegralTypeType,
    KeywordType,
    LineNodeType,
    OperationType,
    PrimitiveType,
    RelationalType,
    ReturnValueType,
    ResolutionType,
    RvalueType,
    StatementType,
    StringType,
    SummationType,
    UserDefinedNameType,
    UserDefinedDeclarationType,
    UserDefinedFunctionReferenceType,
    UserDefinedVariableDeclarationType,
    UserDefinedVariableRefrenceType,
    VariableDeclarationType,
    VariableType,
    VariableReassignmentType,
    WhileExpressionType,
    XEnd,
}
